function interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)

figure('Name','Oscilator cu Retea Wien si diode',... 
 'Units','normalized',...
 'Position',[.1 .1 .8 .8],...
 'NumberTitle','off',...
 'Color', [1 1 1]);
%  uicontrol('Style','text',...
%  'Units','normalized',...
%  'Position',[0.2 0.92 0.5 0.06],...
%  'BackgroundColor',[1 0.5 0.8] ,...
%  'ForegroundColor',[0.28,0.23,0.46],...
%  'FontName','Georgia',...
%  'FontWeight','bold',...
%  'FontSize',25, ...
%  'String','Oscilator cu Retea Wien');

GrupP=uibuttongroup('Visible','on',...
'BackgroundColor',[1 0.5 0.8],...
'ForegroundColor',[0.28,0.23,0.46],...
'Title','Parametrii',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',18,...
'TitlePosition','centertop',...
'Tag','checkbox',...
'Position',[0.02 0.57 .3 0.3]);

  


uicontrol('Style','text',...     %Text C1
    'Units','normalized',... 
    'Position',[0.02 0.8 0.11 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','C1[f]  ',... 
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit C1
    'Units','normalized',... 
    'Position',[0.18 0.8 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(C1),...
    'Callback','C1 = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text C2
    'Units','normalized',... 
    'Position',[0.02 0.55 0.11 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','C2[f]   ',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit C2
    'Units','normalized',... 
    'Position',[0.18 0.55 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(C2),...
    'Callback','C2 = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text E
    'Units','normalized',... 
    'Position',[0.7 0.55 0.11 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',9,...
    'String','E[V] ',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit E
    'Units','normalized',... 
    'Position',[0.86 0.55 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(E),...
    'Callback','E = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text R1
    'Units','normalized',... 
    'Position',[0.02 0.3 0.11 0.2],...   
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','R1[Ω] =  ',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit R1
    'Units','normalized',... 
    'Position',[0.18 0.3 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',9,...
    'String',num2str(R1),...
    'Callback','R1 = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text R2
    'Units','normalized',... 
    'Position',[0.38 0.8 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','R2[Ω]',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit R2
    'Units','normalized',... 
    'Position',[0.53 0.8 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(R2),...
    'Callback','R2 = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text R3
    'Units','normalized',... 
    'Position',[0.37 0.55 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','R3[Ω] =  ',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit R3
    'Units','normalized',... 
    'Position',[0.53 0.55 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(R3),...
    'Callback','R3 = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text Rprim
    'Units','normalized',... 
    'Position',[0.37 0.3 0.11 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',8,...
    'String','Rprim[Ω] ',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit Rprim
    'Units','normalized',... 
    'Position',[0.53 0.3 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(Rprim),...
    'Callback','Rprim = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D);',...
    'Parent', GrupP);
uicontrol('Style','text',...     %Text Rsec
    'Units','normalized',... 
    'Position',[0.7 0.8 0.11 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','Rsec[Ω] =  ',...
    'Parent', GrupP); 
uicontrol('Style','edit',...     %Edit Rsec
    'Units','normalized',... 
    'Position',[0.86 0.8 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(Rsec),...
    'Callback','Rsec = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)',...
    'Parent', GrupP); 
uicontrol('Style','Popup',...
    'Units','Normalized',...
    'Position',[0.05 0.9 0.1 0.05],...
    'FontName','Georgia',...
 'FontWeight','bold',...
 'FontSize',13,...
 'foregroundcolor','w',...
 'BackgroundColor',[0.4660 0.6740 0.1880],...
    'Value', D,...
    'String','conduc diodele|blocare',...
   'Callback', 'D=get(gcbo,''value''),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)');

GrupVi=uibuttongroup('Visible','on',...
'BackgroundColor',[1 0.5 0.8],...
'ForegroundColor',[0.28,0.23,0.46],...
'Title','Valori calculate',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',18,...
'TitlePosition','centertop',...
'Tag','checkbox',...
'Position',[0.35 0.57 0.2 0.3]);

subplot(1,2,2);
img=imread('CIRCUITWIEN.png');
image(img);
axis off;
set(gca, 'Position', [0.6, 0.5, 0.4, 0.4]);
axis image;


if (R1==R2||C1==C2)
    f=1/(2*pi*R1*C1);
    B=1/3;
else 
     f=1/(2*pi*sqrt(R1*R2*C1*C2));
     B=1/(1+R1/R2+C2/C1)
end
uicontrol('Style','text',...     %Text f
    'Units','normalized',... 
    'Position',[0.02 0.55 0.45 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','Frecventa[Hz] ',...
    'Parent',GrupVi); 
uicontrol('Style','text',...     %Edit f
    'Units','normalized',... 
    'Position',[0.52 0.55 0.17 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',8,...
    'String',num2str(f),...
    'Callback','f = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)',...
    'Parent',GrupVi);
T=1/f;
t=0:T/1000:8*T;
I=0.7/((Rprim*rd2)/(Rprim+rd2));
A=I*R3+I*Rsec+0.7; 
Viesire=A*sin(2*pi*f*t);
Vintrare=B*Viesire;

switch D

     case 1
           a=1+((Rsec+((Rprim*rd2)/(Rprim+rd2)))/R3);
          A=I*R3+0.7+I*Rsec;
        Viesire=A*sin(2*pi*f*t);
        Vintrare=B*Viesire;
         if a==3
         else
             Viesire=0; 
         end

     case 2
          a=1+(Rprim+Rsec)/R3;
        I=0.7/Rprim;
        A=I*R3-0.6+I*Rsec;
        Viesire=A*sin(2*pi*f*t);
        Vintrare=B*Viesire;
        if a<3
        else
            Viesire=0;
        
     
        end

end

  if(E<=A) %limitarea amplitudinii oscilatiilor la tensiunea de alimentare
    A=E;
    Viesire=A*sin(2*pi*f*t);
        Vintrare=B*Viesire;
        
elseif(-E>A)
    A=-E;
    Viesire=A*sin(2*pi*f*t);
        Vintrare=B*Viesire;
      
  end
  uicontrol('Style','text',...     %Text amplif
    'Units','normalized',... 
    'Position',[0.02 0.8 0.38 0.2],...   
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','Amplificare  ',...
     'Parent', GrupVi); 

uicontrol('Style','text',...     %Edit amplificare
    'Units','normalized',... 
    'Position',[0.45 0.8 0.11 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(a),...
    'Callback','a = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)',...
     'Parent', GrupVi);
uicontrol('Style','text',...     %Text Amplif semn de iesire
    'Units','normalized',... 
    'Position',[0.02 0.05 0.22 0.2],...  
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','Avo[V]',...
     'Parent', GrupVi); 
uicontrol('Style','text',...     %Edit Amplif semn de iesire
    'Units','normalized',... 
    'Position',[0.3 0.05 0.15 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(A),...
    'Callback','A = str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)',...
     'Parent', GrupVi);
uicontrol('Style','text',...     %Text Vintrare
    'Units','normalized',... 
    'Position',[0.02 0.3 0.22 0.2],... 
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String','Vin[V]',...
     'Parent', GrupVi); 
uicontrol('Style','text',...     %Edit Vintrare
    'Units','normalized',... 
    'Position',[0.26 0.3 0.2 0.2],...
    'BackgroundColor',[0.4940 0.1840 0.5560],...
'ForegroundColor','w',...
'FontName','Georgia',...
'FontWeight','bold',...
'FontSize',10,...
    'String',num2str(A/3),...
    'Callback','Vin= str2num(get (gco,''String'')),close,interfata(E,C1,C2,R1,R2,R3,Rprim,Rsec,rd1,rd2,D)',...
     'Parent', GrupVi);


subplot(212)
plot(t,Viesire, '-dm')
hold on;
plot(t,Vintrare, '-og');
grid on;
title('Semnalul de iesire', 'Color','m');%atribuim un titlu graficului
xlabel('timp [s]', 'Color', 'g'); %scriem pe axa x
ylabel('Amplitudine [V]', 'Color', 'g'); %scriem pe axa y
ylim([-E E])